stages:
  - build-src
  - build-docker
  - docker-registry-master

build-src:
  stage: build-src
  image: debian:buster
  before_script:
    - bash $CI_PROJECT_DIR/scripts/gitlab-ci-build-prescript
  script:
    - export GOPATH=/go
    - export PATH=$PATH:/go/bin
    - cd /go/src/$CI_PROJECT_NAME
    - make devel
    - make prod

build-docker:
  stage: build-docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t commento .

docker-registry-master:
  stage: docker-registry-master
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u tzander -p $CI_JOB_TOKEN
  script:
    - version=v1.8.7
    - apk add git
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${version} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${version}

