stages:
  - go-test
  - build-src
  - build-docker
  - docker-registry-master

build-src:
  stage: build-src
  image: debian:buster
  before_script:
    - bash $CI_PROJECT_DIR/scripts/gitlab-ci-build-prescript
  script:
    - export GOPATH=/go
    - export PATH=$PATH:/go/bin
    - cd /go/src/$CI_PROJECT_NAME
    - make devel
    - make prod

build-docker:
  stage: build-docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t commento .

go-test:
  stage: go-test
  image: golang:1.14
  services:
    - postgres:9.6
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: commento_test
    COMMENTO_POSTGRES: postgres://postgres:postgres@postgres/commento_test?sslmode=disable
  before_script:
    - mkdir -p /go/src /go/bin /go/pkg
    - export GOPATH=/go
    - export PATH=$PATH:/go/bin
    - ln -s $CI_PROJECT_DIR /go/src/$CI_PROJECT_NAME
  script:
    - cd /go/src/$CI_PROJECT_NAME
    - make test

docker-registry-master:
  stage: docker-registry-master
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_TOKEN} ${CI_REGISTRY}
  script:
    - version=v1.8.7
    - apk add git
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${version} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${version}

