version: '3'

services:
  server:
    image: tzander/commento:v1.8.10
    ports:
      - 8080:8080
    environment:
      COMMENTO_ORIGIN: http://commento.de-tz.de:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://postgres:postgres@postgres:5432/commento?sslmode=disable
    depends_on:
      - postgres
    networks:
      - db_network
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data_volume:
