name: Publish Release from master

on:
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build production ready release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build prod
        run: make prod
        
      - name: Make archive
        run: cd build/prod && tar zcvf ../release.tar.gz ./

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
        
      - name: Publish as release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ steps.semvers.outputs.tag }}"
          files: |
            build/release.tar.gz
            
      - name: Push docker image
        uses: ./.github/workflows/docker-image.yml
